# /docker-compose.yml

services:
  # Definimos nuestro servicio de base de datos
  db-postgres:
    # Usamos una versión ligera de PostgreSQL (Alpine)
    image: postgres:15-alpine
    container_name: mtx-metal-erp-postgres-db
    restart: always
    # Configuramos el usuario, contraseña y nombre de la base de datos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mtx_metal_erp
    # Mapeamos el puerto de tu computadora al puerto del contenedor
    ports:
      - "5432:5432"
    # Creamos un volumen para que los datos no se borren si apagamos Docker
    volumes:
      - pgdata:/var/lib/postgresql/data

# Declaramos el volumen que nombramos arriba
volumes:
  pgdata: